"""Shared utilities for ingestion and RAG services."""

from shared.chunker import chunk_text
from shared.contracts import (
    KEY_ANSWER,
    KEY_CHUNKS,
    KEY_CHUNKS_INSERTED,
    KEY_COUNT,
    KEY_DOCUMENT,
    KEY_EMBEDDING,
    KEY_EMBEDDINGS,
    KEY_ID,
    KEY_OK,
    KEY_PAYLOAD,
    KEY_POINTS,
    KEY_QUERY_VECTOR,
    KEY_QUESTION,
    KEY_SOURCE,
    KEY_SOURCES,
    KEY_STATUS,
    KEY_SUCCESS,
    KEY_TEXT,
    KEY_TEXTS,
    KEY_TOP_K,
    KEY_VECTOR,
    PATH_ASK,
    PATH_COMPLETION,
    PATH_EMBED,
    PATH_ENSURE_COLLECTION,
    PATH_HEALTH,
    PATH_INGEST,
    PATH_INGEST_TEXT,
    PATH_SEARCH,
    PATH_UPSERT,
    SOURCE_UNKNOWN,
)
from shared.pdf_parser import extract_text
from shared.prompt_builder import build_prompt

__all__ = [
    "chunk_text",
    "extract_text",
    "build_prompt",
    "KEY_ANSWER",
    "KEY_CHUNKS",
    "KEY_CHUNKS_INSERTED",
    "KEY_COUNT",
    "KEY_DOCUMENT",
    "KEY_EMBEDDING",
    "KEY_EMBEDDINGS",
    "KEY_ID",
    "KEY_OK",
    "KEY_PAYLOAD",
    "KEY_POINTS",
    "KEY_QUESTION",
    "KEY_QUERY_VECTOR",
    "KEY_SOURCE",
    "KEY_SOURCES",
    "KEY_STATUS",
    "KEY_SUCCESS",
    "KEY_TEXT",
    "KEY_TEXTS",
    "KEY_TOP_K",
    "KEY_VECTOR",
    "PATH_ASK",
    "PATH_COMPLETION",
    "PATH_EMBED",
    "PATH_ENSURE_COLLECTION",
    "PATH_HEALTH",
    "PATH_INGEST",
    "PATH_INGEST_TEXT",
    "PATH_SEARCH",
    "PATH_UPSERT",
    "SOURCE_UNKNOWN",
]
